### ISSUE TITLE
headless OAuth

### ISSUE THREAD

**Issue by RoyalTS** [ms32035/RGoogleFit#2]
What's the simplest way to obtain an OAuth token so I can use it non-interactively?

**Comment by ms32035** [comment]
To my knowledge it is not possible to do OAuth2 authentication without a user going through the consent screen once. Storing of refresh tokens is not implemented.

**Comment by RoyalTS** [comment]
So there is no way to use this package in a server setting in which I cannot go through the OAuth dance?
